# [build]
# target = "wasm32-unknown-unknown"
# rustflags = '-Ctarget-feature=+atomics,+bulk-memory,+mutable-globals'

[target.wasm32-unknown-unknown]
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]